### ISSUE TITLE
this project is not completed?

### ISSUE THREAD

**Issue by lchad** [rfreedman/android-ssl#2]
Hi,buddy,your article really help me a lot. 
I have just check out your prject,and then import it into the Android Studio.but I just can not run it.where is RoloActivity? wating for your reply,thanks a lot.

**Comment by rfreedman** [comment]
The project is a bit old, but it is complete (except for the certificates -
you would, of course, have to provide your own).

RoboActivity is from the RoboGuice library - you can see that dependency in
pom.xml

**Comment by lchad** [comment]
Oh, I got it.it is the Android studio just ignore the pox.xml when I import the project.Thanks for your reply.
